### ISSUE TITLE
Linker Exception in "Release" Android build

### ISSUE THREAD

**Issue by mrbelk** [XamFormsExtended/Xfx.Controls#44]
# Bug 
We are using the XfxControls package in a Xamarin.Forms app (Droid and iOS). The Xamarin Forms version is 2.4.0.74863. When we try to compile our primary Droid platform project, we get a build error that the "LinkAssemblies task failed unexpectedly." The actual build error is quoted below. When we build the project in "Debug" mode, it works fine. If we select "Don't Link" in the Linker Behavior section of the Droid project options in the Release configuration, the build completes.

* Version Number of Control: 1.1.3
* Device Tested On: N/A
* Simulator Tested On: N/A

### Affects

- [ ] iOS
- [x] Android (Min version API21, target version API26, Xamarin Android version 8.1.0.25, SDK Tools version 25.2.5, SDK Platform Tools version 27.0.1, SDK Build Tools version 26.0.3)

### Expected Behavior
 Project compiles without any linker errors

### Actual Behavior
Droid project compilation fails with linker exception like this:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void Xfx.Controls.Droid.XfxVisualElementManager::Init(Xamarin.Forms.Platform.Android.IVisualElementRenderer,Xamarin.Forms.Platform.Android.VisualElementRendererFlags)' in assembly: 'Xfx.Controls.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.VisualElementPackager::.ctor(Xamarin.Forms.Platform.Android.IVisualElementRenderer,Xamarin.Forms.VisualElement)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00006] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x00049] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00040] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x00098] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00161] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001a] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:    --- End of inner exception stack trace ---
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00046] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue () [0x00002] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process () [0x00013] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x0000d] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001b] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.LinkContext& context) [0x00070] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x002c8] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute () [0x001fa] in <acf4a3302c8d4a7eaf06af6dce1aafb2>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/msbuild-15.4/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1696,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x0022d] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/msbuild-15.4/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
```

**Comment by ChaseFlorell** [comment]
That's a new class in 1.1.3.
Just to confirm, have you called the `Init()` method in your Android Main Activity?
https://github.com/XamFormsExtended/Xfx.Controls/blob/master/example/Xfx.Controls.Example.Droid/MainActivity.cs#L14

**Comment by mrbelk** [comment]
Yes, but it's the compilation process that fails; not the actual app running. We don't get that far.

**Comment by ChaseFlorell** [comment]
did you try a full clean/rebuild in RELEASE? I wonder if there's a dll mismatch after the update?

**Comment by mrbelk** [comment]
yes I did.

**Comment by ChaseFlorell** [comment]
so if the issue is at compile time, then it's not the Linker. What happens is that the linker strips classes during compile time so that at runtime they're no longer there. I'm leaning more to a dll mismatch.

Make sure you done the following. 
Clean > Close Visual Studio > delete all obj + bin directories > Open Visual Studio > Rebuild

I'm trying to reproduce, but cannot.

**Comment by ChaseFlorell** [comment]
Alternatively, if you can send me a repro, I'll take a look.

**Comment by mrbelk** [comment]
give me a bit to completely clean the solution as well as deleting the contents of the "packages" folder in case the dll mismatch is coming from nuget.

**Comment by mrbelk** [comment]
does 1.1.3 require xamarin forms 2.5, by any chance?

**Comment by mrbelk** [comment]
I've cleaned everything out and still get the linker error. Could it be something with the target android framework version?

**Comment by mrbelk** [comment]
all my xamarin.android.support.* packages are v26.1.0.1.

**Comment by ChaseFlorell** [comment]
I wonder if it makes a difference what the support packages are? Here's what I'm using.

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Annotations" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Compat" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Design" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Fragment" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Transition" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v4" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Forms" version="2.5.0.121934" targetFramework="monoandroid71" />
</packages>
```

**Comment by mrbelk** [comment]
hmmm... let me see if I can downgrade my support libraries and target framework and see what that does

**Comment by toverux** [comment]
Getting the same problem... How can I help you to find the issue?

**Comment by kwacks** [comment]
Also have this problem with linking.
Our only alternative right now is using a native implementation for android. 
Why doesn't linkskip work for this plugin?

**Comment by ChaseFlorell** [comment]
Anyone running into this, please post your stacktrace.

/cc @kwacks @toverux

**Comment by hemantramu** [comment]
We are using the XfxControls package in a Xamarin.Forms app (Droid and iOS). The Xamarin Forms version is 3.6.0.293080. When we try to compile our primary Droid platform project, we get a build error that the "LinkAssemblies task failed unexpectedly." The actual build error is quoted below. When we build the project in "Debug" mode, it works fine. If we select "Don't Link" in the Linker Behavior section of the Droid project options in the Release configuration, the build completes.

Version Number of Control: 1.1.3 / 1.2.1
Device Tested On: Debug Working
Simulator Tested On: N/A
Affects
  iOS - Not Tested Yet
  Android (Min version API19, target version API28, Xamarin Android version 9, SDK Tools version 26.1.1, SDK Platform Tools version 28.0.1, SDK Build Tools version 27.0.3)
Expected Behavior
Project compiles without any linker errors

Actual Behavior
Droid project compilation fails with linker exception like this:

\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void Xfx.Controls.Droid.Renderers.XfxCardViewRendererDroid::Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)' in assembly: 'Xfx.Controls.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.IVisualElementRenderer::add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    --- End of inner exception stack trace ---
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by dlebee** [comment]
any news?

**Comment by MRomeror** [comment]
I have the same issue as @hemantramu Any news? Thanks

**Comment by ChaseFlorell** [comment]
No news yet, would love a repro that I can run to see.

**Comment by ChaseFlorell** [comment]
would anyone be willing to test a fix for me?

**Comment by GeorgeSpring** [comment]
Hello! Getting the same problem...

**Comment by gregersen79** [comment]
Have the same issue.

Xamarin Forms: 3.6.0.344457
Xfx.Controls: 1.2.1
Android libraries: 28.0.0.1

Error:
The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Xfx.Controls.Droid.Renderers.XfxCardViewRendererDroid::Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)' in assembly: 'Xfx.Controls.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.IVisualElementRenderer::add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Project.Forms.Android

**Comment by hcd00045** [comment]
> would anyone be willing to test a fix for me?

I would. Just let me know how. Thanks.

**Comment by MRomeror** [comment]
> would anyone be willing to test a fix for me?

Hi, 
I have created a solution with the latest versions of Xamarin and xfx.Control.
It keeps giving error when compiling in release. I attached the project link.
https://drive.google.com/file/d/1Z9f0moaU_qkGM1RKlbtzG1oIwEuw-PcY/view?usp=sharing

**Comment by thefenry** [comment]
Any update on this? Seems like many have been having the same issue for a while.

**Comment by ArthurConceicao** [comment]
Same issue, haven't found a solution yet

**Comment by Adlorem** [comment]
With newer version of Xamarin there is and issue between system drawing color and xamarin forms color. Only solution is to download source upgrade packages, fix this issue and reference dll locally to your project.

**Comment by rubberydev** [comment]
Hi everyone.

I have the same issue:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Xfx.Controls.Droid.Renderers.XfxCardViewRendererDroid::Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)' in assembly: 'Xfx.Controls.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.IVisualElementRenderer::add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    --- End of inner exception stack trace ---
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Mono.Linker.Pipeline.Process(LinkContext context)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2056,5): error XALNK7000:    at Xamarin.Android.Tasks.AndroidTask.Execute()

Someone has found any solution ?

**Comment by ShivamSingh1** [comment]
Install 1.0.4 version and then remove bin/obj and then rebuild. It's work for me

**Comment by arunrajrgithub** [comment]
Thank you ShivamSingh1.  It worked.  Thank you so much.

**Comment by icamn13** [comment]
Downgrading the version from 1.2.1 to 1.1.3 and then removing bin/obj and clean and rebuild worked for me.
Thanks @ShivamSingh1
